spring.application.name=notification

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.queue-created=${order.created.queue}
rabbitmq.queue.order.update=${order.update.queue}
rabbitmq.queue.order.complete=${order.complete.queue}
aws.acessKey=${ACESS_KEY}
aws.secretKey=${SECRET_KEY}